from typing import Protocol

from rpg_api.domain.models.player import Player


class PlayerRepository(Protocol):
    def get_by_id(self, id_player: int) -> Player: ...
    def get_by_name(self, name: str) -> Player: ...
    def create(self, data: Player) -> Player: ...
